"""empty message

Revision ID: 5b0b0db93c8c
Revises: f269ed023d85
Create Date: 2019-11-07 21:07:24.098033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b0db93c8c'
down_revision = 'f269ed023d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('days_to_maturity', sa.Integer(), nullable=True),
    sa.Column('precip_min', sa.Integer(), nullable=True),
    sa.Column('precip_max', sa.Integer(), nullable=True),
    sa.Column('temp_min', sa.Integer(), nullable=True),
    sa.Column('temp_max', sa.Integer(), nullable=True),
    sa.Column('humid_min', sa.Integer(), nullable=True),
    sa.Column('humid_max', sa.Integer(), nullable=True),
    sa.Column('ph_min', sa.Integer(), nullable=True),
    sa.Column('ph_max', sa.Integer(), nullable=True),
    sa.Column('mat_height', sa.Integer(), nullable=True),
    sa.Column('edible', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('pairings', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('ph', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('crop', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    op.drop_table('plant')
    # ### end Alembic commands ###
