"""empty message

Revision ID: eca1a2722bac
Revises: 5b0b0db93c8c
Create Date: 2019-11-14 22:44:07.825602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca1a2722bac'
down_revision = '5b0b0db93c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('monitor', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'start_time')
    op.drop_column('monitor', 'end_time')
    # ### end Alembic commands ###
